---
- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - postgresRun
  tags:
    - postgres

- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - web
  tags:
    - web