---

- name: Bootstrapping
  gather_facts: False
  hosts: all
  roles:
    - init

- name: Preflight Checks
  gather_facts: True
  hosts: all
  vars_files:
    - "vars/common.yml"
  roles:
    - preflight
  tags:
    - preflight


- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - postgresPack
  tags:
    - postgres

- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - webPack # No, not the js webpack. It's just named that for consistency. Maybe consider renaming
  tags:
    - web

- hosts: all
  vars_files:
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family|lower }}_vars.yml"]
  roles:
    - redis
  tags:
    - redis